name: Krabi

options:
  deploymentTarget: 
    iOS: 15.0
  xcodeVersion: 14.0.1
  useBaseInternationalization: false
  bundleIdPrefix: com.y7matsuo
  groupOrdering:
    - order: [Krabi, Krabi Unit Tests, Domain, Domain Unit Tests, LangkawiDomain, API, API Unit Tests]
    - pattern: '^.*$'
      order: [Source, Resource]
attributes:
  ORGANIZATIONNAME: y7matsuo
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
packages:
  Apollo:
    url: https://github.com/apollographql/apollo-ios.git
    minorVersion: 1.0.2

targetTemplates:
  Main:
    type: application
    platform: iOS
    sources:
      - path: ./Krabi
        excludes:
          - "**/.*.swp"
          - .keep
    preBuildScripts:
      - name: Run Script(lint)
        shell: /bin/sh
        script: |
          swiftlint --fix && swiftlint
          exit 0
    settings:
      base:
        ENABLE_PREVIEWS: true
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        OTHER_LDFLAGS: $(inherited) -ObjC
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - target: Domain
      - target: API
    scheme:
      testTargets:
        - Krabi Unit Tests

  Framework:
    type: framework
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  UnitTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

targets:
  Krabi:
    templates: [Main]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: krabi
        ENVIRONMENT: prod

  Krabi Dev:
    templates: [Main]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: krabi.dev
        ENVIRONMENT: dev
        # ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon Dev

  Krabi Unit Tests:
    templates: [UnitTests]
    sources: 
      - path: ./Krabi Unit Tests
        excludes:
          - .keep
    dependencies:
      - target: Krabi

  Domain:
    templates: [Framework]
    sources:
      - path: ./Domain
        excludes:
          - .keep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: krabi.domain

  Domain Unit Tests:
    templates: [UnitTests]
    sources:
      - path: ./Domain Unit Tests
        excludes:
          - .keep
    dependencies:
      - target: Domain

  API:
    templates: [Framework]
    sources:
      - path: ./API
        excludes:
          - .keep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: krabi.api
    dependencies:
      - target: LangkawiDomain
      - package: Apollo

  API Unit Tests:
    templates: [UnitTests]
    sources:
      - path: ./API Unit Tests
        excludes:
          - .keep
    dependencies:
      - target: API

  LangkawiDomain:
    templates: [Framework]
    sources:
      - path: ./LangkawiDomain
        excludes:
          - .keep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: krabi.domain.langkawi
    dependencies:
      - package: Apollo
